contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #lowinputtrees channel"
    url: https://nfcore.slack.com/channels/lowinputtrees
    about: Discussion about the nf-core/lowinputtrees pipeline
